name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal


- name: Synopsys Polaris SAST Check
  # You may pin to the exact commit or the version.
  # uses: loadbalancerorg/polaris-action@a75ee1c55b503ddbe868d7d4668af895fbfe2fdd
  uses: loadbalancerorg/polaris-action@v2
  with:
    # URL of the polaris server instance
    server_url: 
    # Access token for accessing the polaris server instance
    access_token: 
    # A count of total issues
    total_issues: # optional, default is 0
    # A count of new issues
    new_issues: # optional, default is 0
    # The cli-scan.json file location
    cli_scan_json_file: # optional, default is .synopsys/polaris/cli-scan.json
    # Additional command line options
    command_opts: # optional, default is 
